### ISSUE TITLE
QLSTM: Why one additional dimension?

### ISSUE THREAD

**Issue by benjaminalt** [Orkis-Research/Pytorch-Quaternion-Neural-Networks#4]
Why is the output shape of QLSTM always `(SEQ_LEN, BATCH_SIZE, FEAT_SIZE + 1)`? The comment 

>         # +1 because feat_size = the number on the sequence, and the output one hot will also have a blank dimension so FEAT_SIZE + 1 BLANK 
implies that the output is intended to be interpreted as a sequence of "one-hot quaternions" with a blank dimension. If one uses the QLSTM for a regression task such as sequence-to-sequence prediction on sequences of quaternions, this extra dimension is redundant. If QLSTM is intended to be used like torch.nn.LSTM, shouldn't the output have the shape `(SEQ_LEN, BATCH_SIZE, FEAT_SIZE)`? For classification tasks when one needs a blank dimension, one could wrap QLSTM into a custom nn.Module.

I am modifying QLSTM to have that behavior in my local fork and can make a pull request if you think that makes sense.

**Comment by TParcollet** [comment]
Hi,

The definition of the shape (SEQ_LEN, BATCH_SIZE, FEAT_SIZE + 1) only implies that the FEAT_SIZE correspond to the number of features. If FEAT_SIZE = 8, we will have 2 quaternions. Here, I add + 1 because I need a specific one hot encoding to represent the blank of the copy-task. Consequently, if I encode with FEAT_SIZE = 11, then I'll finally have (SEQ_LEN, BATCH_SIZE, 12). Consequently the output size is (SEQ_LEN, BATCH_SIZE, FEAT_SIZE). Then, for a classification purpose, you can take the SEQ_LENGTH-1 output.
