### ISSUE TITLE
Hi, * is element multiply, I think here should be quaternion multiply. Thank you.

### ISSUE THREAD

**Issue by lihao0214** [Orkis-Research/Pytorch-Quaternion-Neural-Networks#5]
https://github.com/Orkis-Research/Pytorch-Quaternion-Neural-Networks/blob/64d06df67af1eb7ebbc72dad62da10ebee4c4258/recurrent_models.py#L135

**Comment by TParcollet** [comment]
Hi there ! 

I invite to take a look at our paper on QRNN / QLSTM. It's actually a component-wise product, due to the fact that we want the gate to control the amount of information with want to get from each component. Plus, it's not stable at all when used with the Hamilton product (you can try by replace the * by hamilton_product(). Indeed, one must redefine gates in the quaternion domain to do so!
