### ISSUE TITLE
Initialization between (0,1) or (-1,1)?

### ISSUE THREAD

**Issue by shreyaskamathkm** [Orkis-Research/Pytorch-Quaternion-Neural-Networks#8]
Hi,

I was browsing through the paper "QUATERNION RECURRENT NEURAL NETWORKS" and it mentioned that the Quaternion(0,x,y,z) were initialized with rand(0,1). But in the implementation, it is between (-1,1).  Is there a newer paper in which this initialization is explained?

Thank you,
Best,
Shreyas

**Comment by TParcollet** [comment]
Hi ! You won't find any paper on this move to -1,1. This is mostly due to the fact that it doesn't really matter. The most important part is the modulus that contains the scale with respect to the initialization criterion (and the phase). Then initializing a unit vector from a distribution centred in 0 or 0.5 doesn't really change !

**Comment by shreyaskamathkm** [comment]
Awesome! Thank you so much.

I have been trying to train a resnet20 model using quaternion CNN on the cifar10 dataset. However, traditional CNN generally outperforms QCNN by a small margin. I am following the training setup provided [here](https://github.com/akamaster/pytorch_resnet_cifar10).
Have you used QCNN to build any classification system? It would be of great help if you could provide me insights about this?

Thank you,
Best,
Shreyas Kamath
